#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-Xdebug
Version  : 2.8.0alpha1
Release  : 2
URL      : https://pecl.php.net//get/xdebug-2.8.0alpha1.tgz
Source0  : https://pecl.php.net//get/xdebug-2.8.0alpha1.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-Xdebug-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
======
With this debug client you can control the Xdebug server. For compilation and
installation see the INSTALL file.

%package lib
Summary: lib components for the php-Xdebug package.
Group: Libraries

%description lib
lib components for the php-Xdebug package.


%prep
%setup -q -n xdebug-2.8.0alpha1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/xdebug.so
